/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const imageImporter: typeof import('./src/composables/imageImporter')['default']
  const reader: typeof import('./src/composables/reader').reader
}
